@startjson AksEdgeDeploy
<style>
jsonDiagram {
    node {
        FontName Segoe UI SemiBold
        FontColor blue
        FontSize 14
        RoundCorner 10
        LineThickness 1
        separator {
            LineThickness 0.25
            LineColor black
        }
    }
    arrow {
        LineColor blue
        LineThickness 1
        LineStyle 2;5
    }
    highlight {
        BackgroundColor Blue
        FontColor White
    }
}
</style>
#highlight "SchemaVersion"
{
    "SchemaVersion":"1.1",
    "Version":"1.0",
    "AksEdgeProduct" : "Azure Kubernetes Service...",
    "AksEdgeProductUrl" : "URL",
    "Azure":{
        "ClusterName":"String",
        "SubscriptionName":"String",
        "SubscriptionId": "GUID",
        "TenantId":"GUID",
        "ResourceGroupName": "String",
        "ServicePrincipalName" : "String",
        "Location" : "String",
        "Auth": {
            "ServicePrincipalId" : "String",
            "Password" : "String"
        }
    }
    ,
    "DeployOptions":{
        "SingleMachineCluster":"Boolean",
        "NodeType" : ["Linux","LinuxAndWindows"],
        "NetworkPlugin" : ["calico", "flannel"],
        "Headless":"Boolean",
        "TimeoutSeconds":"Int",
        "ClusterJoinToken": "String",
        "ControlPlane": "Boolean",
        "DiscoveryTokenHash": "String",
        "CertificateKey":"String",
        "JoinCluster": "Boolean"
    }
    ,
    "InstallOptions":{
        "InstallPath":"String",
        "VhdxPath":"String"
    }
    ,
    "EndUser":{
        "AcceptEula" : "Boolean"
    }
    ,
    "LinuxVm":{
        "CpuCount" : "2 or more",
        "MemoryInMB" : "2048 or more",
        "DataSizeInGB" : "[2-2000]",
        "Ip4Address": "IPv4",
        "MacAddress": "String",
        "Mtu": "Int"
    }
    ,
    "WindowsVm":{
        "CpuCount" : "2 or more",
        "MemoryInMB" : "2048 or more",
        "Ip4Address": "IPv4",
        "MacAddress": "String",
        "Mtu": "Int"
    }
    ,
    "Network":{
        "VSwitch": {
            "Type" : ["External", "Internal"],
            "AdapterName": "String",
            "Name" : "String"
        }
        ,
        "ControlPlaneEndpointIp":"IPv4",
        "ControlPlaneEndpointPort": "Int",
        "InternetDisabled" : "Boolean",
        "SkipFreeAddressCheck" : "Boolean",
        "Ip4GatewayAddress": "IPv4",
        "Ip4PrefixLength" : "[1-32]",
        "ServiceIPRangeSize" : "[0-127]",
        "ServiceIPRangeStart":"IPv4",
        "ServiceIPRangeEnd":"IPv4",
        "Proxy" : {
            "Http":"URL",
            "Https":"URL",
            "No":"String"
        }
        ,
        "DnsServers":["IPv4","IPv4"]
    }
}
@endjson